#!/usr/bin/env python3
"""Export UI reference fixtures from the original commit, without the port's code."""

import argparse
import pathlib
import os
import subprocess
import tempfile

BASELINE = "c928c477852e75ffcc35f8cd16c7ed03caad7c7f"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare regenerated bytes without replacing the reference")
    parser.add_argument("--target-dir", type=pathlib.Path, help="optional shared Cargo target cache")
    args = parser.parse_args()
    root = pathlib.Path(__file__).resolve().parents[2]
    support = root / "test-support" / "parity"
    scratch = root / "tmp"
    scratch.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="ui-reference-", dir=scratch) as work:
        work = pathlib.Path(work)
        archive = work / "baseline.tar"
        subprocess.run(["git", "archive", "--format=tar", f"--output={archive}", BASELINE], cwd=root, check=True)
        original = work / "original"
        original.mkdir()
        subprocess.run(["tar", "--extract", "--file", str(archive), "--directory", str(original)], check=True)
        crate = original / "profiler-core" / "src"
        (crate / "parity_oracle.rs").write_bytes((support / "ui_oracle.rs").read_bytes())
        with (crate / "lib.rs").open("a") as stream:
            stream.write("\n#[cfg(test)]\nmod parity_oracle;\n")
        output = work / "reference.json"
        env = dict(os.environ, PARITY_OUTPUT=str(output), CARGO_TARGET_DIR=str(args.target_dir.resolve() if args.target_dir else scratch / "ui-reference-target"))
        subprocess.run(["cargo", "test", "--manifest-path", str(original / "Cargo.toml"), "--package", "profiler_core", "--lib", "parity_oracle::export_reference", "--locked", "--offline"], cwd=root, env=env, check=True)
        reference = support / "ui_reference.json"
        if args.check:
            if reference.read_bytes() != output.read_bytes():
                raise SystemExit("UI reference differs from the original-source export")
            print("UI reference reproduces byte for byte")
        else:
            reference.write_bytes(output.read_bytes())
            print(f"Wrote {reference}")


if __name__ == "__main__":
    main()
