//! The C ABI export surface — where the crate's C-facing unsafe concentrates.
//!
//! The host (a C# shim generated by the xtask from `shim/shim.cs.template`)
//! loads this dylib and binds these symbols through `ProfilerNative.GetExport`.
//! Each export's Rust parameter list is the canonical C signature (C types
//! spelled as their Rust equivalents: `c_int` → `i32`, `u64`, `f64`,
//! NUL-terminated strings → `*const c_char`), so the generated shim binds
//! them unchanged and check-abi verifies the table mechanically.
//! `gdextension_entry` is deliberately absent: it is the engine-facing
//! symbol, written by hand in `crate::engine::gdext`.
//!
//! ## Export prefix
//!
//! Every export carries the `spire_profiler_*` prefix, matching the mod's
//! public identity (mod id, class names, log tags, data dir). The ABI is
//! internal to this mod — the shim and the core are always built and
//! installed as a matched pair — and check-abi verifies conformance
//! mechanically.
//!
//! # What unsafe concentrates here
//!
//! `lib.rs` declares `#![deny(unsafe_code)]`, relaxed in exactly three
//! modules: this one, `crate::registration`, and `crate::engine::gdext`
//! (whose allow sits in `engine.rs`, not in `lib.rs`). This module's share
//! of the crate's unsafe Rust is:
//!
//! 1. **C pointer reads** — `with_c_str` dereferences a NUL-terminated string pointer supplied by
//!    the host. The shim never passes null, but null (and any pointer that does not point at valid
//!    NUL-terminated UTF-8) is treated as "" so a malformed argument can never crash the core.
//! 2. **`no_mangle` exports** — the 40 `spire_profiler_*` functions (39 bound by the shim and one
//!    test-only reset export) carry `#[unsafe(no_mangle)] pub unsafe extern "C"` so their symbols
//!    exist for the host. Their bodies contain no other unsafe operations; each one decodes its
//!    arguments and delegates to the safe [`events`] counterpart.
//! 3. **Panic containment** — a Rust panic must never unwind across the C ABI into the game. Every
//!    export runs through `contain`, which catches a panicking core function, reports it through
//!    `crate::fail` (stderr, touches no state), and swallows it. A panic escaping into the host
//!    would crash the game; containment lets the core continue with whatever state the panic left
//!    behind.
//!
//! The other two relaxations quarantine different needs: `registration` owns
//! the per-panel instance casts the FFI callbacks route into, and `gdext`
//! owns the raw engine pointers and interface-function resolution. Any future
//! unsafe requirement belongs behind a safe helper in one of these three.

// The unsafe-op blocks below are exactly the three sources listed above;
// the allow keeps a stricter lint set from demanding safety docs per export.
#![allow(clippy::missing_safety_doc)]

use std::ffi::{CStr, c_char};
use std::path::Path;

use crate::data::events;
use crate::data::state::RunOutcome;
use crate::fail;

/// A null pointer (or one that is not valid NUL-terminated UTF-8) yields
/// "" — a defensive "" beats a segfault in the game's process.
///
/// # Safety
/// `ptr` must be null or a NUL-terminated C string valid for the call.
unsafe fn with_c_str<T>(ptr: *const c_char, f: impl for<'a> FnOnce(&'a str) -> T) -> T {
    let s: &str = if ptr.is_null() {
        ""
    } else {
        // Safety: the caller upholds the contract on `ptr` above.
        unsafe { CStr::from_ptr(ptr) }.to_str().unwrap_or("")
    };
    f(s)
}

/// Catches any panic in `f` so nothing unwinds across the C ABI; the panic
/// is logged through [`fail`] and `on_panic` is returned in its place.
pub(crate) fn contain<T>(name: &str, on_panic: T, f: impl FnOnce() -> T) -> T {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(f)) {
        Ok(value) => value,
        Err(payload) => {
            let detail = if let Some(msg) = payload.downcast_ref::<&str>() {
                (*msg).to_owned()
            } else if let Some(msg) = payload.downcast_ref::<String>() {
                msg.clone()
            } else {
                "non-string panic payload".to_owned()
            };
            fail(format!("panic in {name}: {detail}"));
            on_panic
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_init(data_dir: *const c_char) {
    unsafe {
        with_c_str(data_dir, |data_dir| {
            let data_dir = Path::new(data_dir);
            contain("spire_profiler_init", (), || events::init(data_dir));
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_self_test() {
    contain("spire_profiler_self_test", (), events::self_test);
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_set_run_meta(profile_id: i32) {
    contain("spire_profiler_set_run_meta", (), || {
        events::set_run_meta(profile_id);
    });
}

/// `net_ids` is the comma-joined player NetId list, same shape as
/// `character_ids`; the two pair positionally to build the run's roster.
/// `start_time` is the game's `StartTime` run id (0 when the shim's read
/// failed; the core then stamps its own clock).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_run_started(
    character_ids: *const c_char,
    ascension: i32,
    game_mode: *const c_char,
    seed: *const c_char,
    continued: i32,
    net_ids: *const c_char,
    start_time: i64,
) {
    unsafe {
        with_c_str(character_ids, |character_ids| {
            with_c_str(game_mode, |game_mode| {
                with_c_str(seed, |seed| {
                    with_c_str(net_ids, |net_ids| {
                        contain("spire_profiler_run_started", (), || {
                            events::run_started(
                                character_ids,
                                ascension,
                                game_mode,
                                seed,
                                continued,
                                net_ids,
                                start_time,
                            );
                        });
                    });
                });
            });
        })
    };
}

/// `outcome`: 0 = victory, 1 = defeat, 2 = abandoned.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_run_ended(outcome: i32) {
    contain("spire_profiler_run_ended", (), || {
        events::run_ended(RunOutcome::from_c(outcome))
    });
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_run_suspended() {
    contain("spire_profiler_run_suspended", (), events::run_suspended);
}

/// `player_slot` is the owner slot — TEAM (4) for enemy-owned powers.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_context_begin(
    source_id: *const c_char,
    kind: i32,
    player_slot: i32,
) {
    unsafe {
        with_c_str(source_id, |source_id| {
            contain("spire_profiler_context_begin", (), || {
                events::context_begin(source_id, kind, player_slot);
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_context_end() {
    contain("spire_profiler_context_end", (), events::context_end);
}

/// Re-hooked at the side-level boundary, so the counter counts rounds.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_turn_started() {
    contain("spire_profiler_turn_started", (), events::turn_started);
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_orb_channeled(hash: i32, player_slot: i32) {
    contain("spire_profiler_orb_channeled", (), || {
        events::orb_channeled(hash, player_slot)
    });
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_orb_context_begin(hash: i32, player_slot: i32) {
    contain("spire_profiler_orb_context_begin", (), || {
        events::orb_context_begin(hash, player_slot);
    });
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_potion_used(potion_id: *const c_char, player_slot: i32) {
    unsafe {
        with_c_str(potion_id, |potion_id| {
            contain("spire_profiler_potion_used", (), || {
                events::potion_used(potion_id, player_slot)
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_potion_context_begin(
    potion_id: *const c_char,
    player_slot: i32,
) {
    unsafe {
        with_c_str(potion_id, |potion_id| {
            contain("spire_profiler_potion_context_begin", (), || {
                events::potion_context_begin(potion_id, player_slot)
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_block_pool_clear(player_slot: i32) {
    contain("spire_profiler_block_pool_clear", (), || {
        events::block_pool_clear(player_slot)
    });
}

/// `player_slot` is the owner's slot when the power sits on a player,
/// else 0.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_power_applied(
    power_id: *const c_char,
    amount: i32,
    creature_hash: u64,
    is_player: i32,
    player_slot: i32,
) {
    unsafe {
        with_c_str(power_id, |power_id| {
            contain("spire_profiler_power_applied", (), || {
                events::power_applied(power_id, amount, creature_hash, is_player, player_slot);
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_power_decreased(
    power_id: *const c_char,
    amount: i32,
    creature_hash: u64,
    is_player: i32,
    player_slot: i32,
) {
    unsafe {
        with_c_str(power_id, |power_id| {
            contain("spire_profiler_power_decreased", (), || {
                events::power_decreased(power_id, amount, creature_hash, is_player, player_slot);
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_doom_target_capture(creature_hash: i32, current_hp: i32) {
    contain("spire_profiler_doom_target_capture", (), || {
        events::doom_target_capture(creature_hash, current_hp);
    });
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_doom_kills_completed() {
    contain(
        "spire_profiler_doom_kills_completed",
        (),
        events::doom_kills_completed,
    );
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_osty_summoned(
    source_id: *const c_char,
    source_kind: i32,
    hp_amount: i32,
    player_slot: i32,
) {
    unsafe {
        with_c_str(source_id, |source_id| {
            contain("spire_profiler_osty_summoned", (), || {
                events::osty_summoned(source_id, source_kind, hp_amount, player_slot);
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_osty_killed(player_slot: i32) {
    contain("spire_profiler_osty_killed", (), || {
        events::osty_killed(player_slot)
    });
}

/// The Kill patch fires this on every player death path; damage-kills
/// double-fire idempotently.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_player_died(player_slot: i32) {
    contain("spire_profiler_player_died", (), || {
        events::player_died(player_slot)
    });
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_damage_modifier_contribution(
    modifier_id: *const c_char,
    kind: i32,
    contribution: i32,
    player_slot: i32,
) {
    unsafe {
        with_c_str(modifier_id, |modifier_id| {
            contain("spire_profiler_damage_modifier_contribution", (), || {
                events::damage_modifier_contribution(modifier_id, kind, contribution, player_slot);
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_block_modifier_contribution(
    modifier_id: *const c_char,
    kind: i32,
    contribution: i32,
    player_slot: i32,
) {
    unsafe {
        with_c_str(modifier_id, |modifier_id| {
            contain("spire_profiler_block_modifier_contribution", (), || {
                events::block_modifier_contribution(modifier_id, kind, contribution, player_slot);
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_weak_mitigation(prevented: i32, dealer_hash: u64) {
    contain("spire_profiler_weak_mitigation", (), || {
        events::weak_mitigation(prevented, dealer_hash);
    });
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_buff_mitigation(power_id: *const c_char, prevented: i32) {
    unsafe {
        with_c_str(power_id, |power_id| {
            contain("spire_profiler_buff_mitigation", (), || {
                events::buff_mitigation(power_id, prevented);
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_enemy_hit_context(base_damage: i32, dealer_str: i32) {
    contain("spire_profiler_enemy_hit_context", (), || {
        events::enemy_hit_context(base_damage, dealer_str);
    });
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_combat_started(
    encounter_id: *const c_char,
    encounter_type: *const c_char,
) {
    unsafe {
        with_c_str(encounter_id, |encounter_id| {
            with_c_str(encounter_type, |encounter_type| {
                contain("spire_profiler_combat_started", (), || {
                    events::combat_started(encounter_id, encounter_type);
                });
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_card_play_started(
    card_id: *const c_char,
    play_index: i32,
    play_count: i32,
    card_hash: i32,
    player_slot: i32,
) {
    unsafe {
        with_c_str(card_id, |card_id| {
            contain("spire_profiler_card_play_started", (), || {
                events::card_play_started(card_id, play_index, play_count, card_hash, player_slot);
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_card_play_finished(player_slot: i32) {
    contain("spire_profiler_card_play_finished", (), || {
        events::card_play_finished(player_slot)
    });
}

/// `player_slot` is the creator's slot; the later play keys its row there.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_card_generated(
    card_hash: i32,
    source_id: *const c_char,
    source_kind: i32,
    player_slot: i32,
) {
    unsafe {
        with_c_str(source_id, |source_id| {
            contain("spire_profiler_card_generated", (), || {
                events::card_generated(card_hash, source_id, source_kind, player_slot);
            });
        })
    };
}

/// `player_slot` is `ForgeCmd.Forge`'s player; the forge row keys at it.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_forge(
    source_id: *const c_char,
    source_kind: i32,
    amount: i32,
    player_slot: i32,
) {
    unsafe {
        with_c_str(source_id, |source_id| {
            contain("spire_profiler_forge", (), || {
                events::forge(source_id, source_kind, amount, player_slot);
            });
        })
    };
}

/// `receiver_slot` is the receiving player, or the Osty owner when
/// `osty_flag == 2`; `card_source_slot` is the explicit-card row key.
#[allow(clippy::too_many_arguments)]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_damage_dealt(
    total: i32,
    unblocked: i32,
    blocked: i32,
    card_source_id: *const c_char,
    to_player: i32,
    receiver_hash: u64,
    osty_flag: i32,
    dealer_hash: u64,
    dealer_slot: i32,
    receiver_slot: i32,
    card_source_slot: i32,
) {
    unsafe {
        with_c_str(card_source_id, |card_source_id| {
            contain("spire_profiler_damage_dealt", (), || {
                events::damage_dealt(events::DamageDealt {
                    total,
                    unblocked,
                    blocked,
                    card_source_id,
                    to_player,
                    receiver_hash,
                    osty_flag,
                    dealer_hash,
                    dealer_slot,
                    receiver_slot,
                    card_source_slot,
                });
            });
        })
    };
}

/// `source_slot` is the owner's slot for a card-play block, else the
/// receiver's.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_block_gained(
    amount: i32,
    card_id: *const c_char,
    player_slot: i32,
    source_slot: i32,
) {
    unsafe {
        with_c_str(card_id, |card_id| {
            contain("spire_profiler_block_gained", (), || {
                events::block_gained(amount, card_id, player_slot, source_slot);
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_combat_ended() {
    contain("spire_profiler_combat_ended", (), events::combat_ended);
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_test_reset() {
    contain("spire_profiler_test_reset", (), events::test_reset);
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_run_history_select(
    seed: *const c_char,
    start_time: i64,
    profile: i32,
) {
    unsafe {
        with_c_str(seed, |seed| {
            contain("spire_profiler_run_history_select", (), || {
                events::run_history_select(seed, start_time, profile);
            });
        })
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_run_history_clear() {
    contain("spire_profiler_run_history_clear", (), || {
        events::run_history_clear();
        // The screen's close (and its open prefix) also closes the run
        // panel: the flag must not survive a closed screen.
        crate::ui::run_panel::dismiss_run_manual();
    });
}

/// Context-routed in the core: run-history open flips the run panel's
/// flag, otherwise it flips the combat panel's.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_panel_toggle() {
    contain("spire_profiler_panel_toggle", (), || {
        if crate::data::run_history::screen_open() {
            crate::ui::run_panel::toggle_run_manual();
        } else {
            crate::ui::panel::toggle();
        }
    });
}

/// The core never inspects engine input objects — such calls hang the
/// engine fork — so the event reading stays on the C# side.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_scroll_input(
    panel: i32,
    button_index: i32,
    pressed: i32,
    pan_y: f64,
) {
    contain("spire_profiler_scroll_input", (), || {
        #[expect(
            clippy::cast_possible_truncation,
            reason = "pan deltas are single-pixel precise scrolls; f32 range is ample"
        )]
        crate::ui::scroll::queue_panel_scroll(
            panel,
            i64::from(button_index),
            pressed != 0,
            pan_y as f32,
        );
    });
}

#[cfg(test)]
mod tests {
    use std::ffi::CString;
    use std::fs;

    use super::*;

    fn scratch_dir(label: &str) -> (std::path::PathBuf, CString) {
        let dir = crate::test_util::scratch_dir(label);
        let c_dir = CString::new(dir.to_str().expect("scratch path is UTF-8"))
            .expect("no NUL in scratch path");
        (dir, c_dir)
    }

    /// The exported surface drives the whole pipeline end to end.
    #[test]
    fn exported_surface_runs_the_self_test_pipeline() {
        let (base, c_base) = scratch_dir("spire-profiler-abi-test");
        unsafe {
            spire_profiler_test_reset();
            spire_profiler_init(c_base.as_ptr());
            spire_profiler_self_test();
        }
        assert!(
            base.join("runs.jsonl").exists(),
            "expected runs.jsonl to exist"
        );
        // The combat store: one file per combat, named by its id, under
        // its run's directory — the self-test's combat must be among them.
        let runs_dir = base.join("runs");
        assert!(
            runs_dir.is_dir(),
            "expected {runs_dir} to exist",
            runs_dir = runs_dir.display()
        );
        let mut found = false;
        for run in fs::read_dir(&runs_dir).expect("runs dir readable") {
            let run_dir = run.expect("entry readable").path();
            if !run_dir.is_dir() {
                continue;
            }
            for entry in fs::read_dir(&run_dir).expect("run dir readable") {
                let text = fs::read_to_string(entry.expect("entry readable").path())
                    .expect("combat file readable");
                if text.contains("SELF_TEST") {
                    found = true;
                }
            }
        }
        assert!(found, "the self-test combat must be in the store");
    }

    /// A null string argument must not crash the core: the ABI maps it to "".
    #[test]
    fn null_string_arguments_are_treated_as_empty() {
        let (_base, c_base) = scratch_dir("spire-profiler-abi-null");
        unsafe {
            spire_profiler_test_reset();
            spire_profiler_init(c_base.as_ptr());
            // Empty source ids are skipped by the core; reaching the end of
            // this block without a crash is the assertion.
            spire_profiler_context_begin(std::ptr::null(), 1, 0);
            spire_profiler_context_end();
            spire_profiler_potion_used(std::ptr::null(), 0);
            spire_profiler_potion_context_begin(std::ptr::null(), 0);
            spire_profiler_combat_started(std::ptr::null(), std::ptr::null());
            spire_profiler_combat_ended();
        }
    }

    /// The containment helper must swallow a panic, never unwind into the host.
    #[test]
    fn containment_swallows_a_panicking_core_function() {
        contain("spire_profiler_test_reset", (), || panic!("boom"));
        contain("spire_profiler_test_reset", (), || panic!("str payload"));
    }

    /// Scroll input queues pixels into the addressed panel's pending queue.
    #[test]
    fn scroll_input_export_queues_pixels_per_panel() {
        // Drain leftovers from any prior test on this thread.
        let _ = crate::ui::panel::take_queued_scroll();
        let _ = crate::ui::run_panel::take_queued_scroll();
        unsafe {
            spire_profiler_scroll_input(0, 5, 1, 0.0); // combat: wheel down (+60)
            spire_profiler_scroll_input(1, 0, 0, -10.0); // run: pan (−10 px)
            spire_profiler_scroll_input(0, 4, 0, 0.0); // wheel-up release: nothing
            spire_profiler_scroll_input(7, 5, 1, 0.0); // unknown panel: dropped
        }
        assert_eq!(crate::ui::panel::take_queued_scroll(), 60.0);
        assert_eq!(crate::ui::run_panel::take_queued_scroll(), -10.0);
    }

    /// F8 changes observable state: the run panel's flag, else the combat
    /// toggle.
    #[test]
    fn panel_toggle_export_flips_panel_state_by_run_context() {
        let (_base, c_base) = scratch_dir("spire-profiler-abi-toggle");
        let char_ids = CString::new("IRONCLAD").expect("no NUL");
        let mode = CString::new("Standard").expect("no NUL");
        let seed = CString::new("TOGGLE_SEED").expect("no NUL");
        let net_ids = CString::new("1").expect("no NUL");
        unsafe {
            spire_profiler_test_reset();
            spire_profiler_init(c_base.as_ptr());
        }
        // Outside a run the combat-panel toggle is the documented no-op.
        let before = crate::ui::panel::visible();
        unsafe { spire_profiler_panel_toggle() };
        assert_eq!(crate::ui::panel::visible(), before);
        // Inside a run the same export flips the panel.
        unsafe {
            spire_profiler_run_started(
                char_ids.as_ptr(),
                0,
                mode.as_ptr(),
                seed.as_ptr(),
                0,
                net_ids.as_ptr(),
                0,
            );
            spire_profiler_panel_toggle();
        }
        assert!(crate::ui::panel::visible());
        unsafe { spire_profiler_panel_toggle() };
        assert!(!crate::ui::panel::visible());
        // With the run-history screen open, the toggle routes to the run
        // panel's manual flag instead: every press flips it.
        unsafe {
            spire_profiler_run_history_select(seed.as_ptr(), 0, 1);
            spire_profiler_panel_toggle();
        }
        assert!(crate::ui::run_panel::run_manual_visible());
        unsafe { spire_profiler_panel_toggle() };
        assert!(!crate::ui::run_panel::run_manual_visible());
        unsafe { spire_profiler_panel_toggle() };
        assert!(crate::ui::run_panel::run_manual_visible());
        // The clear that precedes every screen entry resets the flag: the
        // panel starts closed on each visit.
        unsafe { spire_profiler_run_history_clear() };
        assert!(!crate::ui::run_panel::run_manual_visible());
    }

    /// Select/clear drive the whole matching pipeline end to end.
    #[test]
    fn run_history_select_and_clear_exports_drive_the_selection() {
        let (base, c_base) = scratch_dir("spire-profiler-abi-run-history");
        let seed = CString::new("SELF_TEST_SEED").expect("no NUL in seed");
        unsafe {
            spire_profiler_test_reset();
            spire_profiler_init(c_base.as_ptr());
            spire_profiler_self_test();
        }
        // The selection needs the record's exact StartTime: the self-test
        // started its run without one (the session-clock fallback), so
        // read the value it stamped from the written record.
        let text = fs::read_to_string(base.join("runs.jsonl")).expect("runs.jsonl readable");
        let record: serde_json::Value =
            serde_json::from_str(text.lines().next().expect("a run line"))
                .expect("run line parses");
        let start = record["started_at"].as_i64().expect("started_at is i64");
        unsafe { spire_profiler_run_history_select(seed.as_ptr(), start, 1) };
        let view = crate::data::run_history::selected_view().expect("selection stored");
        assert_eq!(view.seed, "SELF_TEST_SEED");
        assert_eq!(view.character, "SELF_TEST_CHAR");
        assert_eq!(view.outcome, Some(RunOutcome::Victory));
        assert_eq!(view.combats.len(), 1);
        assert_eq!(view.combats[0].encounter, "SELF_TEST");

        unsafe { spire_profiler_run_history_clear() };
        assert!(crate::data::run_history::selected_view().is_none());
    }
}
