//! The C ABI export surface — where the crate's C-facing unsafe concentrates.
//!
//! The host (a C# shim generated by the xtask from `shim/shim.cs.template`)
//! loads this dylib and binds these symbols through `ProfilerNative.GetExport`.
//! Each export's Rust parameter list is the canonical C signature (C types
//! spelled as their Rust equivalents: `c_int` → `i32`, `i64`, `f64`,
//! NUL-terminated strings → `*const c_char`), so the generated shim binds
//! them unchanged and check-abi verifies the table mechanically.
//! [`crate::engine::gdext::gdextension_entry`] is deliberately absent:
//! it is the engine-facing symbol, written by hand in
//! [`crate::engine::gdext`].
//!
//! ## Export prefix
//!
//! Every export carries the `spire_profiler_*` prefix, matching the mod's
//! public identity (mod id, class names, log tags, data dir). The ABI is
//! internal to this mod — the shim and the core are always built and
//! installed as a matched pair — and check-abi verifies conformance
//! mechanically.
//!
//! # What unsafe concentrates here
//!
//! `lib.rs` declares `#![deny(unsafe_code)]`, relaxed in exactly three
//! modules: this one, [`crate::registration`], and
//! [`crate::engine::gdext`] (whose allow sits in `engine.rs`, not in
//! `lib.rs`). This module's share of the crate's unsafe Rust is:
//!
//! 1. **C pointer reads** — [`with_c_str`] dereferences a NUL-terminated string pointer supplied by
//!    the host. Null maps to "", and so does a valid C string whose bytes are not UTF-8; any other
//!    pointer violates the unsafe export contract (the matched-pair shim never forms one).
//! 2. **`no_mangle` exports**: the `spire_profiler_*` functions carry `#[unsafe(no_mangle)]` so
//!    their symbols exist for the host. Pointer-free exports are safe to call; pointer-reading
//!    exports require the caller to uphold the C-string contract. Each decodes its arguments and
//!    delegates to [`events`] for the recorded facts or [`crate::ui`] for panel interactions
//!    (toggle, scroll).
//! 3. **Panic containment** — a Rust panic must never unwind across the C ABI into the game. Every
//!    export runs through [`contain`], which catches a panicking core function, reports it through
//!    [`crate::fail`] (stderr, touches no state), and swallows it. A panic escaping into the host
//!    would crash the game; containment lets the core continue with whatever state the panic left
//!    behind.
//!
//! The other two relaxations quarantine different needs:
//! [`crate::registration`] owns the per-panel instance casts the FFI
//! callbacks route into, and [`crate::engine::gdext`] owns the raw engine
//! pointers and interface-function resolution. Any future unsafe
//! requirement belongs behind a safe helper in one of these three.

use std::ffi::{CStr, c_char};
use std::path::Path;

use crate::data::events;
use crate::data::state::RunOutcome;

/// Null yields "", and so does a valid C string whose bytes are not
/// UTF-8. Any other pointer violates the safety contract below.
///
/// # Safety
/// Non-null `ptr` points to initialized readable bytes through a terminating
/// NUL, within one allocation and less than `isize::MAX` bytes from `ptr`.
/// That range remains readable and unmodified until `f` returns.
unsafe fn with_c_str<T>(ptr: *const c_char, f: impl for<'a> FnOnce(&'a str) -> T) -> T {
    let s: &str = if ptr.is_null() {
        ""
    } else {
        // SAFETY: the non-null branch and caller's readable, single-allocation,
        // bounded, unmodified range satisfy CStr::from_ptr through f's return.
        // The higher-ranked callback cannot return a borrow of these bytes.
        unsafe { CStr::from_ptr(ptr) }.to_str().unwrap_or("")
    };
    f(s)
}

std::thread_local! {
    static PANIC_REPORTED: std::cell::Cell<bool> = const { std::cell::Cell::new(false) };
}

/// Returns `on_panic` after an unwinding Rust panic. Payload destructors
/// are suppressed because they can panic; aborting panics remain unrecoverable.
pub(crate) fn contain<T: Copy>(name: &str, on_panic: T, f: impl FnOnce() -> T) -> T {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(f)) {
        Ok(value) => value,
        Err(payload) => {
            let payload = std::mem::ManuallyDrop::new(payload);
            let logged = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                let detail = if let Some(msg) = payload.downcast_ref::<&str>() {
                    *msg
                } else if let Some(msg) = payload.downcast_ref::<String>() {
                    msg.as_str()
                } else {
                    "non-string panic payload"
                };
                crate::fail_once(&PANIC_REPORTED, format_args!("panic in {name}: {detail}"));
            }));
            if let Err(payload) = logged {
                std::mem::forget(payload);
            }
            on_panic
        }
    }
}

/// # Safety
/// Non-null pointers cover initialized readable bytes through a terminating NUL
/// in one allocation, with a total range shorter than `isize::MAX` bytes. Each
/// range remains readable and unmodified throughout this call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_init(data_dir: *const c_char) {
    // SAFETY: pointer arguments satisfy this export's C contract.
    unsafe {
        with_c_str(data_dir, |data_dir| {
            let data_dir = Path::new(data_dir);
            contain("spire_profiler_init", (), || events::init(data_dir));
        })
    };
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_self_test() {
    contain("spire_profiler_self_test", (), events::self_test);
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_set_run_meta(profile_id: i32) {
    contain("spire_profiler_set_run_meta", (), || {
        events::set_run_meta(profile_id);
    });
}

/// `net_ids` is the comma-joined player NetId list, same shape as
/// `character_ids`; the two pair positionally to build the run's roster.
/// `start_time` is the game's `StartTime` run id (0 when the shim's read
/// failed; the identity stays unknown).
///
/// # Safety
/// Non-null pointers cover initialized readable bytes through a terminating NUL
/// in one allocation, with a total range shorter than `isize::MAX` bytes. Each
/// range remains readable and unmodified throughout this call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_run_started(
    character_ids: *const c_char,
    ascension: i32,
    game_mode: *const c_char,
    seed: *const c_char,
    continued: i32,
    net_ids: *const c_char,
    start_time: i64,
) {
    // SAFETY: pointer arguments satisfy this export's C contract.
    unsafe {
        with_c_str(character_ids, |character_ids| {
            with_c_str(game_mode, |game_mode| {
                with_c_str(seed, |seed| {
                    with_c_str(net_ids, |net_ids| {
                        contain("spire_profiler_run_started", (), || {
                            events::run_started(
                                character_ids,
                                ascension,
                                game_mode,
                                seed,
                                continued,
                                net_ids,
                                start_time,
                            );
                        });
                    });
                });
            });
        })
    };
}

/// `outcome`: 0 = victory, 1 = defeat, 2 = abandoned.
#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_run_ended(outcome: i32) {
    contain("spire_profiler_run_ended", (), || {
        events::run_ended(RunOutcome::from_c(outcome))
    });
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_run_suspended() {
    contain("spire_profiler_run_suspended", (), events::run_suspended);
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_test_reset() {
    contain("spire_profiler_test_reset", (), events::test_reset);
}

/// # Safety
/// Non-null pointers cover initialized readable bytes through a terminating NUL
/// in one allocation, with a total range shorter than `isize::MAX` bytes. Each
/// range remains readable and unmodified throughout this call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_run_history_select(
    seed: *const c_char,
    start_time: i64,
    profile: i32,
) {
    // SAFETY: pointer arguments satisfy this export's C contract.
    unsafe {
        with_c_str(seed, |seed| {
            contain("spire_profiler_run_history_select", (), || {
                events::run_history_select(seed, start_time, profile);
            });
        })
    };
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_run_history_clear() {
    contain("spire_profiler_run_history_clear", (), || {
        events::run_history_clear();
        // The screen's close (and its open prefix) also closes the run
        // panel: the flag must not survive a closed screen.
        crate::ui::run_panel::dismiss_run_manual();
    });
}

/// Context-routed in the core: run-history open flips the run panel's
/// flag, otherwise it flips the combat panel's.
#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_panel_toggle() {
    contain("spire_profiler_panel_toggle", (), || {
        if crate::data::run_history::screen_open() {
            crate::ui::run_panel::toggle_run_manual();
        } else {
            crate::ui::panel::toggle();
        }
    });
}

/// The core never inspects engine input objects — such calls hang the
/// engine fork — so the event reading stays on the C# side.
#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_scroll_input(
    panel: i32,
    button_index: i32,
    pressed: i32,
    pan_y: f64,
) {
    contain("spire_profiler_scroll_input", (), || {
        crate::ui::scroll::queue_panel_scroll(panel, i64::from(button_index), pressed != 0, pan_y);
    });
}

/// # Safety
/// Non-null pointers cover initialized readable bytes through a terminating NUL
/// in one allocation, with a total range shorter than `isize::MAX` bytes. Each
/// range remains readable and unmodified throughout this call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_source_capture(
    combat_seq: u64,
    capture_kind: i32,
    instance: u64,
    source_id: *const c_char,
    source_kind: i32,
    source_slot: i32,
    generation_state: i32,
) -> u64 {
    contain("spire_profiler_source_capture", 0, || {
        // SAFETY: the export contract supplies each foreign borrow through callback return.
        unsafe {
            with_c_str(source_id, |source_id| {
                events::source_capture(
                    combat_seq,
                    capture_kind,
                    instance,
                    source_id,
                    source_kind,
                    source_slot,
                    generation_state,
                )
            })
        }
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_source_count(transfer: u64) -> i32 {
    contain("spire_profiler_source_count", -1, || {
        events::source_count(transfer)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_source_destination(transfer: u64, index: i32) -> u64 {
    contain("spire_profiler_source_destination", 0, || {
        events::source_destination(transfer, index)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_source_weight(transfer: u64, index: i32) -> u64 {
    contain("spire_profiler_source_weight", 0, || {
        events::source_weight(transfer, index)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_source_transfer_begin(combat_seq: u64) -> u64 {
    contain("spire_profiler_source_transfer_begin", 0, || {
        events::source_transfer_begin(combat_seq)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_source_transfer_add(
    transfer: u64,
    destination: u64,
    weight: u64,
) -> i32 {
    contain("spire_profiler_source_transfer_add", 0, || {
        events::source_transfer_add(transfer, destination, weight)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_source_transfer_seal(transfer: u64) -> i32 {
    contain("spire_profiler_source_transfer_seal", 0, || {
        events::source_transfer_seal(transfer)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_source_transfer_release(transfer: u64) -> i32 {
    contain("spire_profiler_source_transfer_release", 0, || {
        events::source_transfer_release(transfer)
    })
}

/// # Safety
/// Non-null pointers cover initialized readable bytes through a terminating NUL
/// in one allocation, with a total range shorter than `isize::MAX` bytes. Each
/// range remains readable and unmodified throughout this call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_power_attached(
    combat_seq: u64,
    power_instance: u64,
    power_id: *const c_char,
    owner_creature: u64,
    owner_kind: i32,
    owner_slot: i32,
    amount: i32,
    source_transfer: u64,
) -> i32 {
    contain("spire_profiler_power_attached", 0, || {
        // SAFETY: the export contract supplies each foreign borrow through callback return.
        unsafe {
            with_c_str(power_id, |power_id| {
                events::power_attached(
                    combat_seq,
                    power_instance,
                    power_id,
                    owner_creature,
                    owner_kind,
                    owner_slot,
                    amount,
                    source_transfer,
                )
            })
        }
    })
}

/// # Safety
/// Non-null pointers cover initialized readable bytes through a terminating NUL
/// in one allocation, with a total range shorter than `isize::MAX` bytes. Each
/// range remains readable and unmodified throughout this call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_power_amount_changed(
    combat_seq: u64,
    power_instance: u64,
    power_id: *const c_char,
    owner_creature: u64,
    owner_kind: i32,
    owner_slot: i32,
    old_amount: i32,
    new_amount: i32,
    source_transfer: u64,
) -> i32 {
    contain("spire_profiler_power_amount_changed", 0, || {
        // SAFETY: the export contract supplies each foreign borrow through callback return.
        unsafe {
            with_c_str(power_id, |power_id| {
                events::power_amount_changed(
                    combat_seq,
                    power_instance,
                    power_id,
                    owner_creature,
                    owner_kind,
                    owner_slot,
                    old_amount,
                    new_amount,
                    source_transfer,
                )
            })
        }
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_power_removed(combat_seq: u64, power_instance: u64) -> i32 {
    contain("spire_profiler_power_removed", 0, || {
        events::power_removed(combat_seq, power_instance)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_power_provenance_invalidate(
    combat_seq: u64,
    power_instance: u64,
) -> i32 {
    contain("spire_profiler_power_provenance_invalidate", 0, || {
        events::power_provenance_invalidate(combat_seq, power_instance)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_card_generated(
    combat_seq: u64,
    card_instance: u64,
    source_transfer: u64,
    producer_role: i32,
) -> i32 {
    contain("spire_profiler_card_generated", 0, || {
        events::card_generated(combat_seq, card_instance, source_transfer, producer_role)
    })
}

/// # Safety
/// Non-null pointers cover initialized readable bytes through a terminating NUL
/// in one allocation, with a total range shorter than `isize::MAX` bytes. Each
/// range remains readable and unmodified throughout this call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_card_play_started(
    combat_seq: u64,
    execution_id: u64,
    card_instance: u64,
    card_id: *const c_char,
    player_slot: i32,
    play_index: i32,
    play_count: i32,
    generation_state: i32,
    source_transfer: u64,
) -> u64 {
    contain("spire_profiler_card_play_started", 0, || {
        // SAFETY: the export contract supplies each foreign borrow through callback return.
        unsafe {
            with_c_str(card_id, |card_id| {
                events::card_play_started(
                    combat_seq,
                    execution_id,
                    card_instance,
                    card_id,
                    player_slot,
                    play_index,
                    play_count,
                    generation_state,
                    source_transfer,
                )
            })
        }
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_card_play_finished(play: u64) -> i32 {
    contain("spire_profiler_card_play_finished", 0, || {
        events::card_play_finished(play)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_card_execution_ended(combat_seq: u64, execution_id: u64) -> i32 {
    contain("spire_profiler_card_execution_ended", 0, || {
        events::card_execution_ended(combat_seq, execution_id)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_orb_channeled(
    combat_seq: u64,
    orb_instance: u64,
    source_transfer: u64,
) -> i32 {
    contain("spire_profiler_orb_channeled", 0, || {
        events::orb_channeled(combat_seq, orb_instance, source_transfer)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_orb_context_begin(
    combat_seq: u64,
    orb_instance: u64,
    play: u64,
    owner_slot: i32,
) -> i32 {
    contain("spire_profiler_orb_context_begin", 0, || {
        events::orb_context_begin(combat_seq, orb_instance, play, owner_slot)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_damage_calculation_begin(
    combat_seq: u64,
    source_transfer: u64,
    producer_role: i32,
    segment: i32,
    original_target: u64,
) -> u64 {
    contain("spire_profiler_damage_calculation_begin", 0, || {
        events::damage_calculation_begin(
            combat_seq,
            source_transfer,
            producer_role,
            segment,
            original_target,
        )
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_damage_modifier_contribution(
    calculation: u64,
    source_transfer: u64,
    amount: i32,
) -> i32 {
    contain("spire_profiler_damage_modifier_contribution", 0, || {
        events::damage_modifier_contribution(calculation, source_transfer, amount)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_damage_calculation_enemy_hit(
    calculation: u64,
    dealer_creature: u64,
    base_damage: i32,
    dealer_strength: i32,
) -> i32 {
    contain("spire_profiler_damage_calculation_enemy_hit", 0, || {
        events::damage_calculation_enemy_hit(
            calculation,
            dealer_creature,
            base_damage,
            dealer_strength,
        )
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_damage_calculation_weak_source(
    calculation: u64,
    source_transfer: u64,
) -> i32 {
    contain("spire_profiler_damage_calculation_weak_source", 0, || {
        events::damage_calculation_weak_source(calculation, source_transfer)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_damage_result_append(
    calculation: u64,
    total: i32,
    unblocked: i32,
    blocked: i32,
    result_kind: i32,
    receiver_slot: i32,
    weak_prevented: i32,
) -> i32 {
    contain("spire_profiler_damage_result_append", 0, || {
        events::damage_result_append(
            calculation,
            total,
            unblocked,
            blocked,
            result_kind,
            receiver_slot,
            weak_prevented,
        )
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_damage_calculation_commit(calculation: u64) -> i32 {
    contain("spire_profiler_damage_calculation_commit", 0, || {
        events::damage_calculation_commit(calculation)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_damage_calculation_abort(calculation: u64) -> i32 {
    contain("spire_profiler_damage_calculation_abort", 0, || {
        events::damage_calculation_abort(calculation)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_damage_unattributed(
    combat_seq: u64,
    total: i32,
    unblocked: i32,
    blocked: i32,
    result_kind: i32,
    receiver_slot: i32,
    weak_prevented: i32,
) -> i32 {
    contain("spire_profiler_damage_unattributed", 0, || {
        events::damage_unattributed(
            combat_seq,
            total,
            unblocked,
            blocked,
            result_kind,
            receiver_slot,
            weak_prevented,
        )
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_buff_mitigation(
    combat_seq: u64,
    source_transfer: u64,
    prevented: i32,
) -> i32 {
    contain("spire_profiler_buff_mitigation", 0, || {
        events::buff_mitigation(combat_seq, source_transfer, prevented)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_block_modifier_contribution(
    combat_seq: u64,
    source_transfer: u64,
    amount: i32,
    receiver_slot: i32,
) -> i32 {
    contain("spire_profiler_block_modifier_contribution", 0, || {
        events::block_modifier_contribution(combat_seq, source_transfer, amount, receiver_slot)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_block_gained(
    combat_seq: u64,
    amount: i32,
    source_transfer: u64,
    receiver_slot: i32,
) -> i32 {
    contain("spire_profiler_block_gained", 0, || {
        events::block_gained(combat_seq, amount, source_transfer, receiver_slot)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_forge(combat_seq: u64, source_transfer: u64, amount: i32) -> i32 {
    contain("spire_profiler_forge", 0, || {
        events::forge(combat_seq, source_transfer, amount)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_osty_summoned(
    combat_seq: u64,
    source_transfer: u64,
    hp_amount: i32,
    owner_slot: i32,
) -> i32 {
    contain("spire_profiler_osty_summoned", 0, || {
        events::osty_summoned(combat_seq, source_transfer, hp_amount, owner_slot)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_osty_killed(combat_seq: u64, owner_slot: i32, play: u64) -> i32 {
    contain("spire_profiler_osty_killed", 0, || {
        events::osty_killed(combat_seq, owner_slot, play)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_doom_batch_begin(combat_seq: u64) -> u64 {
    contain("spire_profiler_doom_batch_begin", 0, || {
        events::doom_batch_begin(combat_seq)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_doom_target_capture(
    batch: u64,
    creature_instance: u64,
    doom_power_instance: u64,
    current_hp: i32,
) -> i32 {
    contain("spire_profiler_doom_target_capture", 0, || {
        events::doom_target_capture(batch, creature_instance, doom_power_instance, current_hp)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_doom_kills_completed(batch: u64) -> i32 {
    contain("spire_profiler_doom_kills_completed", 0, || {
        events::doom_kills_completed(batch)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_doom_batch_abort(batch: u64) -> i32 {
    contain("spire_profiler_doom_batch_abort", 0, || {
        events::doom_batch_abort(batch)
    })
}

/// # Safety
/// Non-null pointers cover initialized readable bytes through a terminating NUL
/// in one allocation, with a total range shorter than `isize::MAX` bytes. Each
/// range remains readable and unmodified throughout this call.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn spire_profiler_combat_started(
    encounter_id: *const c_char,
    encounter_type: *const c_char,
) -> u64 {
    contain("spire_profiler_combat_started", 0, || {
        // SAFETY: the export contract supplies each foreign borrow through callback return.
        unsafe {
            with_c_str(encounter_id, |encounter_id| {
                with_c_str(encounter_type, |encounter_type| {
                    events::combat_started(encounter_id, encounter_type)
                })
            })
        }
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_combat_ended(combat_seq: u64) -> i32 {
    contain("spire_profiler_combat_ended", 0, || {
        events::combat_ended(combat_seq)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_turn_started(combat_seq: u64) -> i32 {
    contain("spire_profiler_turn_started", 0, || {
        events::turn_started(combat_seq)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_block_pool_clear(combat_seq: u64, player_slot: i32) -> i32 {
    contain("spire_profiler_block_pool_clear", 0, || {
        events::block_pool_clear(combat_seq, player_slot)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_player_died(combat_seq: u64, player_slot: i32) -> i32 {
    contain("spire_profiler_player_died", 0, || {
        events::player_died(combat_seq, player_slot)
    })
}

#[unsafe(no_mangle)]
pub extern "C" fn spire_profiler_potion_used(combat_seq: u64) -> i32 {
    contain("spire_profiler_potion_used", 0, || {
        events::potion_used(combat_seq)
    })
}

#[cfg(test)]
mod tests {
    use std::ffi::CString;
    use std::fs;

    use super::*;
    use crate::data::state::STATE;

    fn unique_dir(label: &str) -> (std::path::PathBuf, CString) {
        let dir = crate::test_util::unique_dir(label);
        let c_dir = CString::new(
            dir.to_str()
                .expect("the checkout path and fixture label must be UTF-8 for the ABI"),
        )
        .expect("filesystem directory names cannot contain NUL");
        (dir, c_dir)
    }

    #[test]
    fn exported_surface_runs_the_self_test_pipeline() {
        let (base, c_base) = unique_dir("spire-profiler-abi-test");
        // SAFETY: the test forms valid C-string arguments for these exports.
        unsafe {
            spire_profiler_test_reset();
            spire_profiler_init(c_base.as_ptr());
            spire_profiler_self_test();
        }
        assert!(
            base.join("runs.jsonl").exists(),
            "expected runs.jsonl to exist"
        );
        // The combat store: one file per combat, named by its id, under
        // its run's directory — the self-test's combat must be among them.
        let runs_dir = base.join("runs");
        assert!(
            runs_dir.is_dir(),
            "expected {runs_dir} to exist",
            runs_dir = runs_dir.display()
        );
        let mut found = false;
        for run in fs::read_dir(&runs_dir).expect("runs dir readable") {
            let run_dir = run.expect("entry readable").path();
            if !run_dir.is_dir() {
                continue;
            }
            for entry in fs::read_dir(&run_dir).expect("run dir readable") {
                let text = fs::read_to_string(entry.expect("entry readable").path())
                    .expect("combat file readable");
                if text.contains("SELF_TEST") {
                    found = true;
                }
            }
        }
        assert!(found, "the self-test combat must be in the store");
    }

    #[test]
    fn containment_swallows_a_panicking_core_function() {
        contain("spire_profiler_test_reset", (), || panic!("boom"));
        contain("spire_profiler_test_reset", (), || panic!("str payload"));
    }

    #[test]
    fn containment_does_not_drop_an_adversarial_panic_payload() {
        struct PanickingDrop;
        impl Drop for PanickingDrop {
            fn drop(&mut self) {
                panic!("payload destructor escaped containment");
            }
        }
        assert_eq!(
            contain("panic_payload", 17, || std::panic::panic_any(PanickingDrop)),
            17
        );
        assert_eq!(contain("success", 17, || 23), 23);
    }

    #[test]
    fn transfer_exports_contain_reentrant_state_borrows_and_reject_stale_epochs() {
        events::test_reset();
        STATE.with(|cell| {
            cell.borrow_mut().current = Some(crate::data::state::Combat {
                seq: 9,
                ..Default::default()
            });
        });
        let transfer = spire_profiler_source_transfer_begin(9);
        let destination = (9_u64 << 32) | (4 << 3) | 1;
        assert_eq!(
            spire_profiler_source_transfer_add(transfer, destination, 3),
            1
        );
        assert_eq!(spire_profiler_source_transfer_seal(transfer), 1);
        assert_eq!(spire_profiler_source_count(transfer), 1);
        STATE.with(|cell| {
            let _guard = cell.borrow_mut();
            assert_eq!(spire_profiler_source_count(transfer), -1);
            assert_eq!(spire_profiler_source_weight(transfer, 0), 0);
            assert_eq!(spire_profiler_source_destination(transfer, 0), 0);
            assert_eq!(spire_profiler_source_transfer_begin(9), 0);
            assert_eq!(spire_profiler_source_transfer_release(transfer), 0);
        });
        assert_eq!(spire_profiler_source_count(transfer), 1);
        assert_eq!(spire_profiler_source_weight(transfer, 0), 1);
        assert_eq!(spire_profiler_source_destination(transfer, 0), destination);
        STATE.with(|cell| {
            cell.borrow_mut()
                .current
                .as_mut()
                .expect("fixture combat exists")
                .seq = 10;
        });
        assert_eq!(spire_profiler_source_count(transfer), -1);
        assert_eq!(spire_profiler_source_transfer_release(transfer), 0);
        events::test_reset();
    }

    #[test]
    fn scroll_input_export_preserves_routing_and_recovers_from_corrupt_deltas() {
        let data = crate::test_util::unique_dir("spire-profiler-abi-scroll");
        events::test_reset();
        events::init(&data);
        STATE.with(|s| s.borrow_mut().run_ctx = Some(Default::default()));
        crate::ui::panel::dismiss();
        crate::ui::panel::toggle();
        crate::data::run_history::select("", 0, 1);
        crate::ui::run_panel::dismiss_run_manual();
        crate::ui::run_panel::toggle_run_manual();

        for invalid in [f64::NAN, f64::INFINITY, f64::NEG_INFINITY] {
            spire_profiler_scroll_input(0, 5, 1, invalid);
            spire_profiler_scroll_input(0, 0, 0, 12.5);
            spire_profiler_scroll_input(0, 0, 0, invalid);
            spire_profiler_scroll_input(1, 0, 0, -10.0);
            spire_profiler_scroll_input(1, 4, 0, invalid);
            spire_profiler_scroll_input(1, 4, 0, -2.5);
            spire_profiler_scroll_input(1, 4, 1, invalid);
            spire_profiler_scroll_input(7, 5, 1, 0.0);
            spire_profiler_scroll_input(7, 0, 0, invalid);
            assert_eq!(crate::ui::panel::take_queued_scroll(), 72.5);
            assert_eq!(crate::ui::run_panel::take_queued_scroll(), -72.5);
        }
        spire_profiler_scroll_input(0, 0, 0, f64::MAX);
        spire_profiler_scroll_input(1, 0, 0, -f64::MAX);
        assert_eq!(crate::ui::panel::take_queued_scroll(), f32::MAX);
        assert_eq!(crate::ui::run_panel::take_queued_scroll(), -f32::MAX);
        spire_profiler_scroll_input(0, 0, 0, 15.0);
        spire_profiler_scroll_input(1, 0, 0, -12.5);
        assert_eq!(crate::ui::panel::take_queued_scroll(), 15.0);
        assert_eq!(crate::ui::run_panel::take_queued_scroll(), -12.5);
    }

    #[test]
    fn panel_toggle_export_flips_panel_state_by_run_context() {
        let (_base, c_base) = unique_dir("spire-profiler-abi-toggle");
        let char_ids = CString::new("IRONCLAD").expect("no NUL");
        let mode = CString::new("Standard").expect("no NUL");
        let seed = CString::new("TOGGLE_SEED").expect("no NUL");
        let net_ids = CString::new("1").expect("no NUL");
        // SAFETY: the test forms valid C-string arguments for these exports.
        unsafe {
            spire_profiler_test_reset();
            spire_profiler_init(c_base.as_ptr());
        }
        // Outside a run the combat-panel toggle is the documented no-op.
        let before = crate::ui::panel::visible();
        spire_profiler_panel_toggle();
        assert_eq!(crate::ui::panel::visible(), before);
        // Inside a run the same export flips the panel.
        // SAFETY: the test forms valid C-string arguments for these exports.
        unsafe {
            spire_profiler_run_started(
                char_ids.as_ptr(),
                0,
                mode.as_ptr(),
                seed.as_ptr(),
                0,
                net_ids.as_ptr(),
                0,
            );
            spire_profiler_panel_toggle();
        }
        assert!(crate::ui::panel::visible());
        spire_profiler_panel_toggle();
        assert!(!crate::ui::panel::visible());
        // With the run-history screen open, the toggle routes to the run
        // panel's manual flag instead: every press flips it.
        // SAFETY: the test forms valid C-string arguments for these exports.
        unsafe {
            spire_profiler_run_history_select(seed.as_ptr(), 0, 1);
            spire_profiler_panel_toggle();
        }
        assert!(crate::ui::run_panel::run_manual_visible());
        spire_profiler_panel_toggle();
        assert!(!crate::ui::run_panel::run_manual_visible());
        spire_profiler_panel_toggle();
        assert!(crate::ui::run_panel::run_manual_visible());
        // The clear that precedes every screen entry resets the flag: the
        // panel starts closed on each visit.
        spire_profiler_scroll_input(1, 5, 1, 0.0);
        spire_profiler_run_history_clear();
        assert!(!crate::ui::run_panel::run_manual_visible());
        assert_eq!(crate::ui::run_panel::take_queued_scroll(), 0.0);
        // SAFETY: seed is a valid C string; the other arguments are scalars.
        unsafe {
            spire_profiler_run_history_select(seed.as_ptr(), 0, 1);
            spire_profiler_panel_toggle();
        }
        assert_eq!(crate::ui::run_panel::take_queued_scroll(), 0.0);
    }

    #[test]
    fn run_history_select_and_clear_exports_drive_the_selection() {
        let (base, c_base) = unique_dir("spire-profiler-abi-run-history");
        let seed = CString::new("SELF_TEST_SEED").expect("no NUL in seed");
        // SAFETY: the test forms valid C-string arguments for these exports.
        unsafe {
            spire_profiler_test_reset();
            spire_profiler_init(c_base.as_ptr());
            spire_profiler_self_test();
        }
        // Select the identity that traversed the ABI and persisted writer.
        let text = fs::read_to_string(base.join("runs.jsonl")).expect("runs.jsonl readable");
        let record: serde_json::Value =
            serde_json::from_str(text.lines().next().expect("a run line"))
                .expect("run line parses");
        let start = record["started_at"].as_i64().expect("started_at is i64");
        // SAFETY: the test forms valid C-string arguments for these exports.
        unsafe { spire_profiler_run_history_select(seed.as_ptr(), start, 1) };
        let view = crate::data::run_history::selected_view().expect("selection stored");
        assert_eq!(view.seed, "SELF_TEST_SEED");
        assert_eq!(view.character, "SELF_TEST_CHAR");
        assert_eq!(view.outcome, Some(RunOutcome::Victory));
        assert_eq!(view.combats.len(), 1);
        assert_eq!(view.combats[0].encounter, "SELF_TEST");

        spire_profiler_run_history_clear();
        assert!(crate::data::run_history::selected_view().is_none());
    }

    #[test]
    fn null_and_malformed_strings_become_unknown_without_retaining_foreign_bytes() {
        let (_base, c_base) = unique_dir("spire-profiler-abi-strings");
        // SAFETY: fixture buffers include readable NUL bytes and remain immutable during each call.
        unsafe {
            spire_profiler_test_reset();
            spire_profiler_init(c_base.as_ptr());
            let epoch = spire_profiler_combat_started(std::ptr::null(), c"\xff".as_ptr());
            assert_ne!(epoch, 0);
            for pointer in [std::ptr::null(), c"".as_ptr(), c"\xff".as_ptr()] {
                let source = spire_profiler_source_capture(epoch, 1, 1, pointer, 0, 0, 0);
                assert_eq!(spire_profiler_source_count(source), 1);
                assert_eq!(
                    spire_profiler_source_destination(source, 0),
                    (epoch << 32) | (4 << 3) | 1
                );
                assert_eq!(spire_profiler_source_transfer_release(source), 1);
            }
            STATE.with(|cell| {
                let state = cell.borrow();
                let combat = state.current.as_ref().expect("fixture combat exists");
                assert_eq!(
                    (combat.encounter_id.as_str(), combat.encounter_type.as_str()),
                    ("", "")
                );
            });
            assert_eq!(spire_profiler_combat_ended(epoch), 1);
        }
    }
}
