//! Attribution catalog: relic and power hooks selected for a source-context
//! wrap. Hand-curated, never generated: inclusion is a per-body judgment
//! call that weighs the tracked effect against the game's more explicit
//! attribution sources. Re-verify after every game update:
//! `cargo xtask decompile`, then `cargo xtask check-catalog`. Both a stale
//! catalog entry and an unreviewed candidate hook fail the check.
//!
//! Hooks whose ONLY effect is an untracked metric (card draw, energy,
//! stars, healing) are absent. Entries whose hook ALSO produces damage,
//! block, mitigation, or forge stay, including ones named after an
//! untracked resource (LightningRodPower/SpinnerPower channel orbs,
//! GalacticDust/ChildOfTheStarsPower gain block, BlackHolePower deals
//! damage, MiniRegent applies Strength, SpeedsterPower deals damage on
//! non-hand draws, BoundPhylactery summons Osty).
//!
//! Hooks whose only effects are flags, counters, status text, or flash are
//! absent too: an inert context outranks the orb/potion fallbacks while
//! live, so a bookkeeping-only wrap can steal an unrelated async effect's
//! attribution. Their real effects live in unwrapped modifiers (PenNib's
//! ModifyDamageMultiplicative, BurstPower's ModifyCardPlayCount, ...).
//!
//! One entry wraps a non-hook method because the tracked effect lives in it
//! (RollingBoulderPower's Godot-signal damage helper); [`NON_HOOK_ENTRIES`]
//! keeps such exceptions deliberate. [`REVIEWED_CANDIDATES`] is the reviewed
//! half of check-catalog's report: an uncatalogued effect hook absent from
//! it is new and needs a catalog decision, while an entry absent from the
//! report is stale and must be deleted.

/// Relic hooks wrapped in a source-context begin/end pair.
pub const RELICS: [(&str, &str); 85] = [
    ("ScreamingFlagon", "BeforeSideTurnEnd"),
    ("StoneCalendar", "BeforeSideTurnEnd"),
    ("ParryingShield", "AfterSideTurnEnd"),
    ("CharonsAshes", "AfterCardExhausted"),
    ("ForgottenSoul", "AfterCardExhausted"),
    ("FestivePopper", "AfterPlayerTurnStart"),
    ("MercuryHourglass", "AfterPlayerTurnStart"),
    ("MrStruggles", "AfterPlayerTurnStart"),
    ("Metronome", "AfterOrbChanneled"),
    ("Tingsha", "AfterCardDiscarded"),
    ("Kusarigama", "AfterCardPlayed"),
    ("LetterOpener", "AfterCardPlayed"),
    ("LostWisp", "AfterCardPlayed"),
    ("CloakClasp", "BeforeSideTurnEnd"),
    ("FakeOrichalcum", "BeforeSideTurnEnd"),
    ("Orichalcum", "BeforeSideTurnEnd"),
    ("RippleBasin", "BeforeSideTurnEnd"),
    ("ToughBandages", "AfterCardDiscarded"),
    ("IntimidatingHelmet", "BeforeCardPlayed"),
    ("HornCleat", "AfterBlockCleared"),
    ("CaptainsWheel", "AfterBlockCleared"),
    ("GalacticDust", "AfterStarsSpent"),
    ("DaughterOfTheWind", "AfterCardPlayed"),
    ("OrnamentalFan", "AfterCardPlayed"),
    ("Permafrost", "AfterCardPlayed"),
    ("TuningFork", "AfterCardPlayed"),
    ("BlessedAntler", "BeforeHandDraw"),
    ("HandDrill", "AfterBlockBroken"),
    ("Kunai", "AfterCardPlayed"),
    ("Shuriken", "AfterCardPlayed"),
    ("RainbowRing", "AfterCardPlayed"),
    ("RedSkull", "AfterRoomEntered"),
    ("RedSkull", "AfterCurrentHpChanged"),
    ("Akabeko", "AfterSideTurnStart"),
    ("BagOfMarbles", "BeforeSideTurnStart"),
    ("Brimstone", "AfterSideTurnStart"),
    ("RedMask", "BeforeSideTurnStart"),
    ("SlingOfCourage", "AfterRoomEntered"),
    ("EmotionChip", "AfterPlayerTurnStart"),
    ("Vajra", "AfterRoomEntered"),
    ("Girya", "AfterRoomEntered"),
    ("DataDisk", "AfterRoomEntered"),
    ("Anchor", "BeforeCombatStart"),
    ("FakeAnchor", "BeforeCombatStart"),
    ("BronzeScales", "AfterRoomEntered"),
    ("EmberTea", "AfterRoomEntered"),
    ("TeaOfDiscourtesy", "BeforeCombatStart"),
    ("FencingManual", "AfterSideTurnStart"),
    ("PhilosophersStone", "AfterCreatureAddedToCombat"),
    ("PhilosophersStone", "AfterRoomEntered"),
    ("BoundPhylactery", "BeforeCombatStart"),
    ("BoundPhylactery", "AfterEnergyResetLate"),
    ("PhylacteryUnbound", "BeforeCombatStart"),
    ("PhylacteryUnbound", "AfterSideTurnStart"),
    ("CrackedCore", "BeforeSideTurnStart"),
    ("InfusedCore", "AfterSideTurnStart"),
    ("Gorget", "AfterRoomEntered"),
    ("OddlySmoothStone", "AfterRoomEntered"),
    ("SwordOfJade", "AfterRoomEntered"),
    ("BoneFlute", "AfterAttack"),
    ("ReptileTrinket", "AfterPotionUsed"),
    ("BeltBuckle", "AfterPotionUsed"),
    ("BeltBuckle", "AfterPotionProcured"),
    ("BeltBuckle", "AfterObtained"),
    ("SparklingRouge", "AfterBlockCleared"),
    ("SelfFormingClay", "AfterDamageReceived"),
    ("TwistedFunnel", "BeforeSideTurnStart"),
    ("FuneraryMask", "BeforeHandDraw"),
    ("SymbioticVirus", "AfterSideTurnStart"),
    ("OrangeDough", "AfterSideTurnStart"),
    ("BigHat", "AfterSideTurnStart"),
    ("DiamondDiadem", "AfterSideTurnStart"),
    ("Sai", "AfterSideTurnStart"),
    ("Crossbow", "AfterSideTurnStart"),
    ("VexingPuzzlebox", "AfterPlayerTurnStart"),
    ("ChoicesParadox", "AfterPlayerTurnStart"),
    ("Regalite", "AfterCardGeneratedForCombat"),
    ("HelicalDart", "AfterCardPlayed"),
    ("TheAbacus", "AfterShuffle"),
    ("Toolbox", "BeforeHandDraw"),
    ("NinjaScroll", "BeforeHandDraw"),
    ("RadiantPearl", "BeforeHandDraw"),
    ("ToastyMittens", "AfterPlayerTurnStart"),
    ("MiniRegent", "AfterStarsSpent"),
    ("BurningSticks", "AfterCardExhausted"),
];

/// Power hooks wrapped in a source-context begin/end pair.
pub const POWERS: [(&str, &str); 64] = [
    ("RagePower", "AfterCardPlayed"),
    ("FlameBarrierPower", "AfterDamageReceived"),
    ("FeelNoPainPower", "AfterCardExhausted"),
    ("PlatingPower", "BeforeSideTurnEndEarly"),
    ("InfernoPower", "AfterDamageReceived"),
    ("InfernoPower", "AfterPlayerTurnStart"),
    ("JuggernautPower", "AfterBlockGained"),
    ("CrimsonMantlePower", "AfterPlayerTurnStart"),
    ("DemonFormPower", "AfterSideTurnStart"),
    ("EntropyPower", "AfterPlayerTurnStart"),
    ("RupturePower", "AfterDamageReceived"),
    ("RupturePower", "AfterCardPlayed"),
    ("PoisonPower", "AfterSideTurnStart"),
    ("PanachePower", "AfterCardPlayed"),
    ("AfterimagePower", "AfterCardPlayed"),
    ("SneakyPower", "AfterCardPlayed"),
    ("EnvenomPower", "AfterDamageGiven"),
    ("NoxiousFumesPower", "AfterSideTurnStart"),
    ("InfiniteBladesPower", "BeforeHandDraw"),
    ("StranglePower", "AfterCardPlayed"),
    ("StormPower", "AfterCardPlayed"),
    ("HailstormPower", "BeforeSideTurnEnd"),
    ("ConsumingShadowPower", "AfterSideTurnEnd"),
    ("LoopPower", "AfterPlayerTurnStart"),
    ("LightningRodPower", "AfterEnergyReset"),
    ("SpinnerPower", "AfterEnergyReset"),
    ("CreativeAiPower", "BeforeHandDraw"),
    ("HelloWorldPower", "BeforeHandDraw"),
    ("ThunderPower", "AfterOrbEvoked"),
    ("DanseMacabrePower", "BeforeCardPlayed"),
    ("CountdownPower", "AfterSideTurnStart"),
    ("HauntPower", "AfterCardPlayed"),
    ("ShroudPower", "AfterPowerAmountChanged"),
    ("SleightOfFleshPower", "AfterPowerAmountChanged"),
    ("OblivionPower", "AfterCardPlayed"),
    ("CallOfTheVoidPower", "BeforeHandDraw"),
    ("NecroMasteryPower", "AfterCurrentHpChanged"),
    ("DevourLifePower", "AfterCardPlayed"),
    ("SpiritOfAshPower", "BeforeCardPlayed"),
    ("ReaperFormPower", "AfterDamageGiven"),
    ("SicEmPower", "AfterDamageGiven"),
    ("BlackHolePower", "AfterCardPlayed"),
    ("BlackHolePower", "AfterStarsGained"),
    ("ChildOfTheStarsPower", "AfterStarsSpent"),
    ("PillarOfCreationPower", "AfterCardGeneratedForCombat"),
    ("ArsenalPower", "AfterCardGeneratedForCombat"),
    ("MonologuePower", "AfterCardPlayed"),
    ("MonarchsGazePower", "AfterDamageGiven"),
    ("SpectrumShiftPower", "BeforeHandDraw"),
    ("ReflectPower", "AfterDamageReceived"),
    ("FurnacePower", "AfterSideTurnStart"),
    ("SentryModePower", "BeforeHandDraw"),
    ("BlockNextTurnPower", "AfterBlockCleared"),
    ("EnragePower", "AfterCardPlayed"),
    ("GalvanicPower", "AfterCardPlayed"),
    ("JugglingPower", "BeforeCardPlayed"),
    ("PrepTimePower", "AfterSideTurnStart"),
    ("ThornsPower", "BeforeDamageReceived"),
    ("SmokestackPower", "AfterCardGeneratedForCombat"),
    ("RollingBoulderPower", "AfterPlayerTurnStart"),
    ("RollingBoulderPower", "DoDamage"),
    ("SpeedsterPower", "AfterCardDrawn"),
    ("SerpentFormPower", "AfterCardPlayed"),
    ("TrashToTreasurePower", "AfterCardGeneratedForCombat"),
];

/// Catalogued methods that intentionally are not hook overrides.
pub const NON_HOOK_ENTRIES: [(&str, &str, &str); 1] =
    [("Powers", "RollingBoulderPower", "DoDamage")];

/// Uncatalogued hooks reviewed and deliberately left out of the catalog.
pub const REVIEWED_CANDIDATES: [(&str, &str, &str); 75] = [
    ("Powers", "BeaconOfHopePower", "AfterBlockGained"),
    ("Powers", "BiasedCognitionPower", "AfterSideTurnStart"),
    ("Powers", "CacophonyPower", "AfterCardDrawn"),
    ("Powers", "CalamityPower", "AfterCardPlayed"),
    ("Powers", "ConcoctPower", "AfterDamageGiven"),
    ("Powers", "ConstrictPower", "AfterSideTurnEnd"),
    ("Powers", "CoolantPower", "AfterSideTurnStart"),
    ("Powers", "CorrosiveWavePower", "AfterCardDrawn"),
    ("Powers", "CoveredPower", "AfterApplied"),
    ("Powers", "CrabRagePower", "AfterDeath"),
    ("Powers", "CurlUpPower", "AfterCardPlayed"),
    ("Powers", "DemisePower", "AfterSideTurnEnd"),
    ("Powers", "DisintegrationPower", "AfterSideTurnEndLate"),
    ("Powers", "GravityPower", "AfterCardPlayed"),
    ("Powers", "HammerTimePower", "AfterForge"),
    ("Powers", "HighVoltagePower", "AfterSideTurnEnd"),
    ("Powers", "IllusionPower", "AfterApplied"),
    ("Powers", "MagicBombPower", "AfterSideTurnEnd"),
    ("Powers", "MonologuePower", "AfterSideTurnEnd"),
    ("Powers", "NemesisPower", "AfterSideTurnEnd"),
    ("Powers", "NeurosurgePower", "AfterSideTurnStart"),
    ("Powers", "NightmarePower", "BeforeHandDraw"),
    ("Powers", "PainfulStabsPower", "AfterAttack"),
    ("Powers", "PaleBlueDotPower", "AfterCardPlayed"),
    ("Powers", "PersonalHivePower", "AfterDamageReceived"),
    ("Powers", "PlatingPower", "BeforeSideTurnStart"),
    ("Powers", "PossessSpeedPower", "AfterDeath"),
    ("Powers", "PossessStrengthPower", "AfterDeath"),
    ("Powers", "RampartPower", "AfterSideTurnStart"),
    ("Powers", "RavenousPower", "AfterDeath"),
    ("Powers", "RitualPower", "AfterSideTurnEnd"),
    ("Powers", "SelfFormingClayPower", "AfterBlockCleared"),
    ("Powers", "ShadowStepPower", "AfterSideTurnStart"),
    ("Powers", "SkittishPower", "AfterAttack"),
    ("Powers", "SoulboundPower", "AfterCardGeneratedForCombat"),
    ("Powers", "SuckPower", "AfterAttack"),
    ("Powers", "SummonNextTurnPower", "AfterPlayerTurnStart"),
    ("Powers", "SurprisePower", "AfterDeath"),
    ("Powers", "TankPower", "AfterApplied"),
    (
        "Powers",
        "TemporaryDexterityPower",
        "AfterPowerAmountChanged",
    ),
    ("Powers", "TemporaryDexterityPower", "AfterSideTurnEnd"),
    ("Powers", "TemporaryDexterityPower", "BeforeApplied"),
    ("Powers", "TemporaryFocusPower", "AfterPowerAmountChanged"),
    ("Powers", "TemporaryFocusPower", "AfterSideTurnEnd"),
    ("Powers", "TemporaryFocusPower", "BeforeApplied"),
    (
        "Powers",
        "TemporaryStrengthPower",
        "AfterPowerAmountChanged",
    ),
    ("Powers", "TemporaryStrengthPower", "AfterSideTurnEnd"),
    ("Powers", "TemporaryStrengthPower", "BeforeApplied"),
    ("Powers", "TenderPower", "AfterCardPlayed"),
    ("Powers", "TenderPower", "AfterSideTurnEnd"),
    ("Powers", "TerritorialPower", "AfterSideTurnEnd"),
    ("Powers", "TheBombPower", "BeforeSideTurnEnd"),
    ("Powers", "ToricToughnessPower", "AfterBlockCleared"),
    ("Powers", "UnderworldPower", "AfterDamageGiven"),
    ("Powers", "VitalSparkPower", "AfterCardPlayed"),
    ("Powers", "WitheringPresencePower", "AfterCardPlayed"),
    ("Powers", "WraithFormPower", "AfterSideTurnStart"),
    ("Relics", "ArchaicTooth", "AfterObtained"),
    ("Relics", "Astrolabe", "AfterObtained"),
    ("Relics", "BeltBuckle", "AfterPotionDiscarded"),
    ("Relics", "BeltBuckle", "BeforeCombatStart"),
    ("Relics", "BiiigHug", "AfterShuffle"),
    ("Relics", "Byrdpip", "AfterObtained"),
    ("Relics", "Claws", "AfterObtained"),
    ("Relics", "FakeSneckoEye", "AfterObtained"),
    ("Relics", "FakeSneckoEye", "BeforeCombatStart"),
    ("Relics", "FragrantMushroom", "AfterObtained"),
    ("Relics", "LeafyPoultice", "AfterObtained"),
    ("Relics", "MusicBox", "AfterCardPlayed"),
    ("Relics", "NewLeaf", "AfterObtained"),
    ("Relics", "PandorasBox", "AfterObtained"),
    ("Relics", "PrecariousShears", "AfterObtained"),
    ("Relics", "RoyalPoison", "AfterPlayerTurnStart"),
    ("Relics", "SneckoEye", "AfterObtained"),
    ("Relics", "SneckoEye", "BeforeCombatStart"),
];
