//! Attribution catalog: every relic and power hook that can produce combat
//! effects, with the hook method to wrap. Verified against the v0.110.1
//! decompiled source, one snapshot behind the game_version PIN (v0.111.0):
//! re-decompile the pinned version before trusting a citation.
//!
//! Hooks whose ONLY effect is an untracked metric (card draw, energy,
//! stars, healing) are absent. Entries whose hook ALSO produces damage,
//! block, mitigation, or forge stay, including ones named after an
//! untracked resource (LightningRodPower/SpinnerPower channel orbs,
//! GalacticDust/ChildOfTheStarsPower gain block, BlackHolePower deals
//! damage, MiniRegent applies Strength, SpeedsterPower deals damage on
//! non-hand draws, BoundPhylactery summons Osty).
//!
//! Hooks whose only effects are flags, counters, status text, or flash are
//! absent too: an inert context outranks the orb/potion fallbacks while
//! live, so a bookkeeping-only wrap can steal an unrelated async effect's
//! attribution. Their real effects live in unwrapped modifiers (PenNib's
//! ModifyDamageMultiplicative, ...).

/// Relic hooks wrapped in a source-context begin/end pair.
pub const RELICS: [(&str, &str); 87] = [
    ("ScreamingFlagon", "BeforeSideTurnEnd"),
    ("StoneCalendar", "BeforeSideTurnEnd"),
    ("ParryingShield", "AfterSideTurnEnd"),
    ("CharonsAshes", "AfterCardExhausted"),
    ("ForgottenSoul", "AfterCardExhausted"),
    ("FestivePopper", "AfterPlayerTurnStart"),
    ("MercuryHourglass", "AfterPlayerTurnStart"),
    ("MrStruggles", "AfterPlayerTurnStart"),
    ("Metronome", "AfterOrbChanneled"),
    ("Tingsha", "AfterCardDiscarded"),
    ("Kusarigama", "AfterCardPlayed"),
    ("LetterOpener", "AfterCardPlayed"),
    ("LostWisp", "AfterCardPlayed"),
    ("CloakClasp", "BeforeSideTurnEnd"),
    ("FakeOrichalcum", "BeforeSideTurnEnd"),
    ("Orichalcum", "BeforeSideTurnEnd"),
    ("RippleBasin", "BeforeSideTurnEnd"),
    ("ToughBandages", "AfterCardDiscarded"),
    ("IntimidatingHelmet", "BeforeCardPlayed"),
    ("HornCleat", "AfterBlockCleared"),
    ("CaptainsWheel", "AfterBlockCleared"),
    ("GalacticDust", "AfterStarsSpent"),
    ("DaughterOfTheWind", "AfterCardPlayed"),
    ("OrnamentalFan", "AfterCardPlayed"),
    ("Permafrost", "AfterCardPlayed"),
    ("TuningFork", "AfterCardPlayed"),
    ("BlessedAntler", "BeforeHandDraw"),
    ("HandDrill", "AfterBlockBroken"),
    ("Kunai", "AfterCardPlayed"),
    ("Shuriken", "AfterCardPlayed"),
    ("RainbowRing", "AfterCardPlayed"),
    ("RedSkull", "AfterCurrentHpChanged"),
    ("Akabeko", "AfterSideTurnStart"),
    ("BagOfMarbles", "BeforeSideTurnStart"),
    ("Brimstone", "AfterSideTurnStart"),
    ("RedMask", "BeforeSideTurnStart"),
    ("SlingOfCourage", "AfterRoomEntered"),
    ("EmotionChip", "AfterPlayerTurnStart"),
    ("Vajra", "AfterRoomEntered"),
    ("Girya", "AfterRoomEntered"),
    ("DataDisk", "AfterRoomEntered"),
    ("Anchor", "BeforeCombatStart"),
    ("BronzeScales", "AfterRoomEntered"),
    ("EmberTea", "AfterRoomEntered"),
    ("Bellows", "AfterPlayerTurnStart"),
    ("BoneTea", "AfterPlayerTurnStart"),
    ("TeaOfDiscourtesy", "BeforeCombatStart"),
    ("FencingManual", "AfterSideTurnStart"),
    ("PaelsTooth", "AfterCombatEnd"),
    ("PhilosophersStone", "AfterCreatureAddedToCombat"),
    ("PhilosophersStone", "AfterRoomEntered"),
    ("PaelsWing", "OnSacrifice"),
    ("BoundPhylactery", "BeforeCombatStart"),
    ("BoundPhylactery", "AfterEnergyResetLate"),
    ("PhylacteryUnbound", "BeforeCombatStart"),
    ("PhylacteryUnbound", "AfterSideTurnStart"),
    ("CrackedCore", "BeforeSideTurnStart"),
    ("InfusedCore", "AfterSideTurnStart"),
    ("Gorget", "AfterRoomEntered"),
    ("OddlySmoothStone", "AfterRoomEntered"),
    ("StoneCracker", "AfterRoomEntered"),
    ("SwordOfJade", "AfterRoomEntered"),
    ("BoneFlute", "AfterAttack"),
    ("ReptileTrinket", "AfterPotionUsed"),
    ("BeltBuckle", "AfterPotionUsed"),
    ("BeltBuckle", "AfterPotionProcured"),
    ("BeltBuckle", "AfterObtained"),
    ("SparklingRouge", "AfterBlockCleared"),
    ("SelfFormingClay", "AfterDamageReceived"),
    ("TwistedFunnel", "BeforeSideTurnStart"),
    ("FuneraryMask", "BeforeHandDraw"),
    ("SymbioticVirus", "AfterSideTurnStart"),
    ("OrangeDough", "AfterSideTurnStart"),
    ("BigHat", "AfterSideTurnStart"),
    ("Sai", "AfterSideTurnStart"),
    ("Crossbow", "AfterSideTurnStart"),
    ("VexingPuzzlebox", "AfterPlayerTurnStart"),
    ("ChoicesParadox", "AfterPlayerTurnStart"),
    ("RazorTooth", "AfterCardPlayed"),
    ("HelicalDart", "AfterCardPlayed"),
    ("TheAbacus", "AfterShuffle"),
    ("Toolbox", "BeforeHandDraw"),
    ("NinjaScroll", "BeforeHandDraw"),
    ("RadiantPearl", "BeforeHandDraw"),
    ("ToastyMittens", "AfterPlayerTurnStart"),
    ("MiniRegent", "AfterStarsSpent"),
    ("BurningSticks", "AfterCardExhausted"),
];

/// Power hooks wrapped in a source-context begin/end pair.
pub const POWERS: [(&str, &str); 71] = [
    ("RagePower", "AfterCardPlayed"),
    ("FlameBarrierPower", "AfterDamageReceived"),
    ("FeelNoPainPower", "AfterCardExhausted"),
    ("PlatingPower", "BeforeSideTurnEndEarly"),
    ("InfernoPower", "AfterDamageReceived"),
    ("InfernoPower", "AfterPlayerTurnStart"),
    ("JuggernautPower", "AfterBlockGained"),
    ("CrimsonMantlePower", "AfterPlayerTurnStart"),
    ("DemonFormPower", "AfterSideTurnStart"),
    ("RupturePower", "AfterDamageReceived"),
    ("RupturePower", "AfterCardPlayed"),
    ("PoisonPower", "AfterSideTurnStart"),
    ("PanachePower", "AfterCardPlayed"),
    ("AfterimagePower", "AfterCardPlayed"),
    ("SneakyPower", "AfterCardPlayed"),
    ("EnvenomPower", "AfterDamageGiven"),
    ("NoxiousFumesPower", "AfterSideTurnStart"),
    ("InfiniteBladesPower", "BeforeHandDraw"),
    ("StranglePower", "BeforeCardPlayed"),
    ("StranglePower", "AfterCardPlayed"),
    ("StormPower", "AfterCardPlayed"),
    ("HailstormPower", "BeforeSideTurnEnd"),
    ("SubroutinePower", "BeforeCardPlayed"),
    ("ConsumingShadowPower", "AfterSideTurnEnd"),
    ("LoopPower", "AfterPlayerTurnStart"),
    ("LightningRodPower", "AfterEnergyReset"),
    ("SpinnerPower", "AfterEnergyReset"),
    ("CreativeAiPower", "BeforeHandDraw"),
    ("HelloWorldPower", "BeforeHandDraw"),
    ("ThunderPower", "AfterOrbEvoked"),
    ("DanseMacabrePower", "BeforeCardPlayed"),
    ("CountdownPower", "AfterSideTurnStart"),
    ("HauntPower", "AfterCardPlayed"),
    ("ShroudPower", "AfterPowerAmountChanged"),
    ("SleightOfFleshPower", "AfterPowerAmountChanged"),
    ("OblivionPower", "AfterCardPlayed"),
    ("CallOfTheVoidPower", "BeforeHandDraw"),
    ("NecroMasteryPower", "AfterCurrentHpChanged"),
    ("DevourLifePower", "AfterCardPlayed"),
    ("SpiritOfAshPower", "BeforeCardPlayed"),
    ("ReaperFormPower", "AfterDamageGiven"),
    ("SicEmPower", "AfterDamageGiven"),
    ("BlackHolePower", "AfterCardPlayed"),
    ("BlackHolePower", "AfterStarsGained"),
    ("ChildOfTheStarsPower", "AfterStarsSpent"),
    ("PillarOfCreationPower", "AfterCardGeneratedForCombat"),
    ("ArsenalPower", "AfterCardGeneratedForCombat"),
    ("MonologuePower", "AfterCardPlayed"),
    ("MonarchsGazePower", "AfterDamageGiven"),
    ("SpectrumShiftPower", "BeforeHandDraw"),
    ("ReflectPower", "AfterDamageReceived"),
    ("FurnacePower", "AfterSideTurnStart"),
    ("SentryModePower", "BeforeHandDraw"),
    ("BlockNextTurnPower", "AfterBlockCleared"),
    ("EnragePower", "AfterCardPlayed"),
    ("GalvanicPower", "AfterCardPlayed"),
    ("JugglingPower", "BeforeCardPlayed"),
    ("PrepTimePower", "AfterSideTurnStart"),
    ("MayhemPower", "AfterAutoPrePlayPhaseEntered"),
    ("BurstPower", "AfterModifyingCardPlayCount"),
    ("BurstPower", "AfterSideTurnEnd"),
    ("EchoFormPower", "AfterModifyingCardPlayCount"),
    ("MasterPlannerPower", "AfterCardPlayed"),
    ("ThornsPower", "BeforeDamageReceived"),
    ("RegenPower", "BeforeSideTurnEndEarly"),
    ("SmokestackPower", "AfterCardGeneratedForCombat"),
    ("RollingBoulderPower", "AfterPlayerTurnStart"),
    ("RollingBoulderPower", "DoDamage"),
    ("SpeedsterPower", "AfterCardDrawn"),
    ("SerpentFormPower", "AfterCardPlayed"),
    ("TrashToTreasurePower", "AfterCardGeneratedForCombat"),
];
