//! xtask: the workspace's single command runner. One xshell::Shell is
//! created in main and passed by reference to every subcommand, so all
//! spawned commands run rooted at the workspace directory.

use std::path::Path;

use anyhow::Result;
use xshell::{Shell, cmd};

mod build;
mod bundle;
mod catalog;
mod check_abi;
mod check_citations;
mod check_docs;
mod cross;
mod decompile;
mod discover;
mod dotnet;
mod game_version;
mod git;
mod headless;
mod install;
mod md;
mod release;
mod shim;
mod zig;

mod flags {
    // xflags emits unqualified type names, so PathBuf must be in scope here.
    use std::path::PathBuf;

    xflags::xflags! {
        src "./src/main.rs"

        cmd xtask {
            /// Format check (rust + markdown) + clippy + nextest + citation check:
            /// the commit gate.
            cmd smoke {}
            /// Install the pinned toolchain and verify the dev tools.
            cmd install-tool {}
            /// Assemble the cross-platform mod bundle under target/mods/.
            cmd build {}
            /// Rebuild and package the mod as release zips under dist/.
            cmd release {}
            /// Copy the mod into the game's mods directory.
            cmd install-mod {}
            /// Install the mod and boot the game headless (self-test verdict).
            cmd headless-test {}
            /// Check shim<->core ABI conformance.
            cmd check-abi {}
            /// Fail on cargo doc warnings and report the comment-density budget.
            cmd check-docs {
                /// How many top comment contributors to list (default: 10).
                optional --top top: usize
            }
            /// Fail on file:line citations in comments and docs.
            cmd check-citations {}
            /// Reflow the project markdown docs to the pinned width.
            cmd fmt-md {
                /// Check for wrapping drift without rewriting.
                optional --check
            }
            /// Recover the game's Godot source for educational study (GDRE Tools).
            cmd decompile {
                /// Output directory (default: tmp/sts2-decompiled).
                optional output_dir: PathBuf
                /// Skip the overwrite confirmation prompt.
                optional -y, --yes
            }
        }
    }

    // generated start
    // The following code is generated by `xflags` macro.
    // Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
    #[derive(Debug)]
    pub struct Xtask {
        pub subcommand: XtaskCmd,
    }

    #[derive(Debug)]
    pub enum XtaskCmd {
        Smoke(Smoke),
        InstallTool(InstallTool),
        Build(Build),
        Release(Release),
        InstallMod(InstallMod),
        HeadlessTest(HeadlessTest),
        CheckAbi(CheckAbi),
        CheckDocs(CheckDocs),
        CheckCitations(CheckCitations),
        FmtMd(FmtMd),
        Decompile(Decompile),
    }

    #[derive(Debug)]
    pub struct Smoke;

    #[derive(Debug)]
    pub struct InstallTool;

    #[derive(Debug)]
    pub struct Build;

    #[derive(Debug)]
    pub struct Release;

    #[derive(Debug)]
    pub struct InstallMod;

    #[derive(Debug)]
    pub struct HeadlessTest;

    #[derive(Debug)]
    pub struct CheckAbi;

    #[derive(Debug)]
    pub struct CheckDocs {
        pub top: Option<usize>,
    }

    #[derive(Debug)]
    pub struct CheckCitations;

    #[derive(Debug)]
    pub struct FmtMd {
        pub check: bool,
    }

    #[derive(Debug)]
    pub struct Decompile {
        pub output_dir: Option<PathBuf>,

        pub yes: bool,
    }

    impl Xtask {
        #[allow(dead_code)]
        pub fn from_env_or_exit() -> Self {
            Self::from_env_or_exit_()
        }

        #[allow(dead_code)]
        pub fn from_env() -> xflags::Result<Self> {
            Self::from_env_()
        }

        #[allow(dead_code)]
        pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
            Self::from_vec_(args)
        }
    }
    // generated end
}

fn main() -> Result<()> {
    let shell = shell()?;
    let args = flags::Xtask::from_env_or_exit();

    match args.subcommand {
        flags::XtaskCmd::Smoke(_) => smoke(&shell),
        flags::XtaskCmd::InstallTool(_) => install_tool(&shell),
        flags::XtaskCmd::Build(_) => build::build(&shell),
        flags::XtaskCmd::Release(_) => release::release(&shell),
        flags::XtaskCmd::InstallMod(_) => install::install_mod(&shell),
        flags::XtaskCmd::HeadlessTest(_) => headless::headless_test(&shell),
        flags::XtaskCmd::CheckAbi(_) => check_abi::run(),
        flags::XtaskCmd::CheckDocs(flags) => check_docs::check_docs(&shell, flags.top),
        flags::XtaskCmd::CheckCitations(_) => check_citations::run(),
        flags::XtaskCmd::FmtMd(flags) => md::fmt_md(flags.check),
        flags::XtaskCmd::Decompile(flags) => {
            decompile::decompile(&shell, flags.output_dir, flags.yes)
        }
    }
}

/// Rooted at the workspace, so subcommands behave the same from anywhere.
fn shell() -> Result<Shell> {
    let shell = Shell::new()?;
    shell.change_dir(workspace_root());
    Ok(shell)
}

/// Derived at compile time, so it works from any working directory, any
/// checkout, and even a bare binary invoked without cargo.
pub(crate) fn workspace_root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask manifest always lives directly below the workspace root")
}

/// Streamed in 64 KiB chunks (the zig tarball and GDRE zip are 50-100 MB,
/// so never loaded whole).
pub(crate) fn sha256_file(path: &Path) -> Result<String> {
    use std::io::Read;

    use sha2::{Digest, Sha256};

    let file = std::fs::File::open(path)?;
    let mut hasher = Sha256::new();
    let mut reader = std::io::BufReader::new(file);
    let mut buf = [0u8; 64 * 1024];
    loop {
        let n = reader.read(&mut buf)?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    Ok(format!("{:x}", hasher.finalize()))
}

/// Fail with the remedy, not a raw spawn error, before the work runs.
pub(crate) fn ensure_cli(shell: &Shell, tool: &str, probe_arg: &str, purpose: &str) -> Result<()> {
    Shell::cmd(shell, tool).arg(probe_arg).read().map_err(|_| {
        anyhow::anyhow!(
            "{purpose} needs the {tool} CLI, which is not on PATH; install it (macOS ships \
             it with the OS, Linux via the distro's {tool} package)"
        )
    })?;
    Ok(())
}

fn smoke(shell: &Shell) -> Result<()> {
    cmd!(shell, "cargo fmt --all -- --check").run()?;
    md::fmt_md(true)?;
    check_citations::run()?;
    cmd!(
        shell,
        "cargo clippy --workspace --all-targets --all-features -- --deny warnings"
    )
    .run()?;
    cmd!(shell, "cargo nextest run --workspace").run()?;
    Ok(())
}

/// The build bootstraps these lazily when missing, so install-tool is the
/// optional up-front/offline path, not a prerequisite.
fn install_tool(shell: &Shell) -> Result<()> {
    // Same host gate as build: the toolchain bootstraps are Unix-only.
    discover::Platform::detect()?;

    let tool_checks: [(&[&str], String, String, Option<&str>); 3] = [
        (
            &["cargo", "nextest", "--version"],
            "cargo-nextest --locked".to_owned(),
            "cargo-nextest".to_owned(),
            None,
        ),
        (
            &["cargo", "insta", "--version"],
            "cargo-insta --locked".to_owned(),
            "cargo-insta".to_owned(),
            None,
        ),
        (
            &["cargo-zigbuild", "--version"],
            format!(
                "cargo-zigbuild --version {} --locked",
                cross::ZIGBUILD_VERSION
            ),
            format!("cargo-zigbuild {}", cross::ZIGBUILD_VERSION),
            Some(cross::ZIGBUILD_VERSION),
        ),
    ];
    for (probe, install_spec, label, expected_version) in tool_checks {
        match Shell::cmd(shell, probe[0]).args(&probe[1..]).read() {
            Ok(output) if expected_version.is_none_or(|v| output.contains(v)) => {
                println!("{label}: {}", output.trim());
            }
            _ => {
                if let Some(expected_version) = expected_version {
                    println!("{label}: wrong version; upgrading to the pinned {expected_version}");
                }
                let argv = install_tool_argv(&install_spec);
                cmd!(shell, "cargo {argv...}").run()?;
                println!("{label}: installed");
            }
        }
    }

    crate::dotnet::ensure_bootstrap(shell)?;
    crate::zig::ensure_bootstrap(shell)?;
    crate::cross::ensure_targets(shell)?;

    println!("install-tool: all tools present");
    Ok(())
}

/// The spec arrives as one string; it must reach cargo as separate argv
/// elements — a single argument would name a bogus crate and always fail.
fn install_tool_argv(install_spec: &str) -> Vec<&str> {
    let mut argv = vec!["+stable", "install"];
    argv.extend(install_spec.split_whitespace());
    argv
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn install_tool_argv_splits_the_spec_into_separate_arguments() {
        assert_eq!(
            install_tool_argv("cargo-zigbuild --version 0.23.0 --locked"),
            vec![
                "+stable",
                "install",
                "cargo-zigbuild",
                "--version",
                "0.23.0",
                "--locked",
            ]
        );
        assert_eq!(
            install_tool_argv("cargo-insta --locked"),
            vec!["+stable", "install", "cargo-insta", "--locked"]
        );
    }
}
